export function pilotHtml(publishableKey: string) {
  const safeKey = JSON.stringify(publishableKey);
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>2Nspira Stripe Payment Pilot</title><script src="https://js.stripe.com/v3/"></script>
<style>body{font:16px system-ui;margin:0;background:#f5f7fa;color:#14213d}main{max-width:900px;margin:40px auto;padding:24px}section{background:#fff;border:1px solid #dce3eb;border-radius:12px;padding:20px;margin:16px 0}button{background:#087e8b;color:#fff;border:0;border-radius:7px;padding:10px 14px}input,select{padding:9px;margin:4px;min-width:180px}.muted{color:#596779}pre{white-space:pre-wrap;background:#eef2f6;padding:12px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:16px}</style></head>
<body><main><h1>Stripe payment pilot</h1><p class="muted">Test mode only · Demo Property Management Client · raw payment credentials go directly to Stripe.</p>
<section><h2>1. Demo customer</h2><button id="customer">Create Stripe Customer</button><pre id="customerOut">Not created</pre></section>
<div class="grid"><section><h2>2. Save card</h2><button data-setup="card">Start card setup</button><div id="card-element"></div><button id="confirmCard" disabled>Save card</button><pre id="cardOut">Not saved</pre></section>
<section><h2>3. Save ACH</h2><p class="muted">Uses Stripe Financial Connections / approved bank verification flow.</p><button data-setup="ach">Start bank setup</button><div id="ach-element"></div><button id="confirmAch" disabled>Link bank</button><pre id="achOut">Not saved</pre></section></div>
<section><h2>4. Billing schedule</h2><input id="service" value="Website Hosting"><input id="amount" type="number" value="22500"><select id="frequency"><option>monthly</option><option>annual</option><option>specific</option></select><input id="chargeDate" type="date"><input id="fee" type="number" value="0" aria-label="Convenience fee cents"><button id="schedule">Authorize schedule</button><pre id="scheduleOut">No schedule</pre></section>
<section><h2>5. Manual payment</h2><p class="muted">Manual ACH and Zelle are client-initiated. Reporting a payment never marks the invoice paid.</p>
<select id="manualMethod"><option value="manual_ach">ACH Bank Transfer — $0 convenience fee</option><option value="zelle">Zelle — manual payment</option></select>
<input id="invoiceId" value="invoice-demo-1001" aria-label="Invoice ID"><input id="manualAmount" type="number" value="1000000" aria-label="Invoice amount cents">
<input id="clientUser" value="demo-client-user" aria-label="Client user"><input id="manualReference" placeholder="Optional confirmation/reference"><input id="manualNote" placeholder="Optional client note">
<pre id="manualInstructions">Select a method to view approved instructions.</pre>
<label><input id="manualAck" type="checkbox"> I confirm that I initiated this payment. I understand the invoice remains pending until 2Nspira confirms receipt.</label><br>
<button id="reportSent">I have sent this payment</button><pre id="manualOut">AWAITING_PAYMENT</pre>
<div><input id="opsUser" value="2nspira-ops-user" aria-label="2Nspira user"><input id="opsKey" type="password" placeholder="Operator key" aria-label="Operator key"><input id="opsNote" placeholder="Verification/reconciliation note">
<button id="confirmReceived">Confirm payment received</button> <button id="paymentNotFound">Payment not found</button> <button id="requestInfo">Request more information</button></div></section>
<section><h2>History / status</h2><button id="refresh">Refresh</button><pre id="state">No data</pre></section>
<script>
const stripe=Stripe(${safeKey}); let customerId=new URLSearchParams(location.search).get('customer')||undefined,methodId,type,elements,setupIntentId,scheduleId,manualPaymentId;
if(customerId){customerOut.textContent=JSON.stringify({id:customerId,source:'existing Stripe Customer'},null,2)}
const post=async(url,body)=>{const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw Error(j.error||'Request failed');return j};
const postOps=async(url,body)=>{const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json','x-2nspira-operator-key':opsKey.value},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw Error(j.error||'Request failed');return j};
customer.onclick=async()=>{const j=await post('/api/customers',{name:'Demo Property Management Client'});customerId=j.id;customerOut.textContent=JSON.stringify(j,null,2)};
document.querySelectorAll('[data-setup]').forEach(b=>b.onclick=async()=>{if(!customerId)return alert('Create customer first');type=b.dataset.setup;const j=await post('/api/setup-intents',{customerId,type});setupIntentId=j.id;elements=stripe.elements({clientSecret:j.clientSecret});const el=elements.create('payment',{layout:'tabs'});const target=type==='card'?'#card-element':'#ach-element';el.mount(target);document.querySelector(type==='card'?'#confirmCard':'#confirmAch').disabled=false});
async function confirmSetup(kind){const result=await stripe.confirmSetup({elements,confirmParams:{return_url:location.href},redirect:'if_required'});if(result.error)throw result.error;const intent=result.setupIntent;const pm=typeof intent.payment_method==='string'?intent.payment_method:intent.payment_method.id;const safe=await post('/api/payment-methods/save',{customerId,paymentMethodId:pm});methodId=pm;type=kind;document.querySelector(kind==='card'?'#cardOut':'#achOut').textContent=JSON.stringify(safe,null,2)}
confirmCard.onclick=()=>confirmSetup('card').catch(e=>cardOut.textContent=e.message);confirmAch.onclick=()=>confirmSetup('ach').catch(e=>achOut.textContent=e.message);
schedule.onclick=async()=>{const date=chargeDate.value?new Date(chargeDate.value+'T12:00:00Z'):new Date(Date.now()+4*86400000);const j=await post('/api/schedules',{organization:'demo-property-management',service:service.value,customerId,paymentMethodId:methodId,paymentType:type,amount:Number(amount.value),convenienceFee:Number(fee.value),frequency:frequency.value,nextChargeAt:date.toISOString(),authorizationText:'I authorize 2Nspira to charge the selected payment method according to this schedule.',authorizationVersion:'v1.0'});scheduleId=j.schedule.id;scheduleOut.textContent=JSON.stringify(j,null,2)};
async function loadManualInstructions(){const j=await fetch('/api/manual-payment-instructions/'+manualMethod.value).then(r=>r.json());manualInstructions.textContent=j.instructions}manualMethod.onchange=loadManualInstructions;loadManualInstructions();
reportSent.onclick=async()=>{const j=await post('/api/manual-payments/report',{invoiceId:invoiceId.value,organization:'demo-property-management',method:manualMethod.value,expectedAmount:Number(manualAmount.value),clientUserId:clientUser.value,acknowledgmentAccepted:manualAck.checked,acknowledgmentVersion:'v1.0',acknowledgmentText:'I confirm that I initiated this payment using the selected payment method. I understand that the invoice will remain pending until 2Nspira confirms receipt of the funds.',referenceNumber:manualReference.value,clientNote:manualNote.value});manualPaymentId=j.payment.id;manualOut.textContent='Payment reported as sent. We will mark the invoice paid after the funds are received and verified.\n\n'+JSON.stringify(j,null,2)};
async function manualAction(action){if(!manualPaymentId)return alert('Report a payment first');const j=await postOps('/api/manual-payments/'+manualPaymentId+'/'+action,{userId:opsUser.value,note:opsNote.value});manualOut.textContent=JSON.stringify(j,null,2)}
confirmReceived.onclick=()=>manualAction('confirm');paymentNotFound.onclick=()=>manualAction('not-found');requestInfo.onclick=()=>manualAction('request-info');
refresh.onclick=async()=>{state.textContent=JSON.stringify(await fetch('/api/pilot-state').then(r=>r.json()),null,2)};
</script></main></body></html>`;
}
