import Link from "next/link";
import { notFound } from "next/navigation";
import { getPortalContext } from "@/lib/portal/context";
import { getInvoiceForOrganization } from "@/lib/portal/data";
import { date, DemoAction, money, PreviewNotice, StatusChip } from "@/components/portal/PortalUI";

export default async function InvoiceDetailPage({ params }: { params: Promise<{ invoiceId: string }> }) {
  const { organization } = await getPortalContext(); const { invoiceId } = await params; const record = await getInvoiceForOrganization(organization.id, invoiceId); if (!record) notFound();
  const { invoice, serviceName, lines, payments } = record;
  return <><div className="portal-back"><Link href="/account/invoices">← All invoices</Link></div><PreviewNotice>This invoice is demonstration data. PDF delivery and online payment are not live in Milestone 1.</PreviewNotice><article className="portal-invoice-detail"><header><div><p className="portal-kicker">INVOICE</p><h1>{invoice.invoiceNumber}</h1><StatusChip status={invoice.status} /></div><div className="portal-heading-actions"><DemoAction reason="PDF invoice delivery is not live">Download PDF</DemoAction>{invoice.balance > 0 && <DemoAction reason="Online payment is not live">Pay balance</DemoAction>}</div></header><div className="portal-invoice-parties"><div><span>From</span><strong>2Nspira LLC</strong><p>11215 72nd Rd<br />Forest Hills, NY<br />hello@2nspira.com</p></div><div><span>Bill to</span><strong>{organization.legalName ?? organization.name}</strong><p>{organization.address}<br />{organization.billingEmail}</p></div><dl><div><dt>Issue date</dt><dd>{date(invoice.issueDate)}</dd></div><div><dt>Due date</dt><dd>{date(invoice.dueDate)}</dd></div><div><dt>Service</dt><dd>{serviceName ?? "Professional services"}</dd></div></dl></div><div className="portal-line-items"><div className="portal-line-head"><span>Description</span><span>Qty</span><span>Rate</span><span>Amount</span></div>{lines.map((line) => <div className="portal-line-row" key={line.id}><span>{line.description}</span><span data-label="Qty">{line.quantity}</span><span data-label="Rate">{money(line.unitPrice)}</span><strong data-label="Amount">{money(line.amount)}</strong></div>)}</div><div className="portal-invoice-totals"><dl><div><dt>Subtotal</dt><dd>{money(invoice.subtotal)}</dd></div><div><dt>Tax</dt><dd>{money(invoice.tax)}</dd></div><div><dt>Total</dt><dd>{money(invoice.total)}</dd></div>{payments.map((payment) => <div key={payment.id}><dt>Payment · {date(payment.paidAt)}</dt><dd>−{money(payment.amount)}</dd></div>)}<div className="total"><dt>Remaining balance</dt><dd>{money(invoice.balance)}</dd></div></dl></div></article></>;
}
