import { getPortalContext, canManageBilling } from "@/lib/portal/context";
import { getPortalData } from "@/lib/portal/data";
import { date, DemoAction, money, PageHeading, SectionCard, StatusChip, TextLink } from "@/components/portal/PortalUI";

export default async function BillingPage() {
  const { organization, role } = await getPortalContext(); const data = await getPortalData(organization.id);
  const balance = data.invoices.reduce((sum, row) => sum + row.invoice.balance, 0); const defaultMethod = data.paymentMethods.find((method) => method.isDefault);
  return <><PageHeading eyebrow="BILLING" title="A clear view of what’s due" description="Balances, scheduled charges, payments, and billing preferences in one place." action={canManageBilling(role) ? <DemoAction>Pay now</DemoAction> : undefined} />
    <section className="portal-billing-hero"><div><span>Current balance</span><strong>{money(balance)}</strong><small>{balance ? "Payment provider connection required to pay online" : "No payment is currently due"}</small></div><div><span>Autopay</span><strong>{data.autopay ? "On" : "Off"}</strong><small>{data.autopay ? "Explicit authorization recorded" : "Not enabled"}</small></div><div><span>Default method</span><strong>{defaultMethod ? `${defaultMethod.brand} •••• ${defaultMethod.lastFour}` : "Not set"}</strong><small><TextLink href="/account/payment-methods">Manage methods</TextLink></small></div></section>
    <div className="portal-two-column"><SectionCard title="Upcoming charges" subtitle="Based on active engagement billing dates."><div className="portal-list">{data.engagements.filter((row) => row.engagement.nextBillingDate).map(({ engagement, service }) => <div className="portal-list-row" key={engagement.id}><div><strong>{service.name}</strong><span>{date(engagement.nextBillingDate)}</span></div><strong>{engagement.amount ? money(engagement.amount) : "TBD"}</strong></div>)}</div></SectionCard><SectionCard title="Billing contact"><dl className="portal-detail-list"><div><dt>Organization</dt><dd>{organization.name}</dd></div><div><dt>Email</dt><dd>{organization.billingEmail}</dd></div><div><dt>Role</dt><dd>{role.replaceAll("_", " ")}</dd></div></dl></SectionCard></div>
    <SectionCard title="Payment history" action={<TextLink href="/account/invoices">View invoices</TextLink>}><div className="portal-table" role="table" aria-label="Payment history"><div className="portal-table-head" role="row"><span>Date</span><span>Method</span><span>Amount</span><span>Status</span></div>{data.payments.map(({ payment, method }) => <div className="portal-table-row" role="row" key={payment.id}><span data-label="Date">{date(payment.paidAt)}</span><span data-label="Method">{method ? `${method.brand} •••• ${method.lastFour}` : "Manual"}</span><strong data-label="Amount">{money(payment.amount)}</strong><span data-label="Status"><StatusChip status={payment.status} /></span></div>)}</div></SectionCard>
    <SectionCard title="Alternative payment" subtitle="Zelle is handled separately from the secure payment-method wallet."><div className="portal-zelle"><div><strong>Pay via Zelle</strong><p>Contact 2Nspira for current payment instructions and include your invoice number. Payments are recorded after confirmation.</p></div><a href="mailto:billing@2nspira.com?subject=Zelle%20payment%20instructions" className="portal-secondary-button">Request instructions</a></div></SectionCard>
  </>;
}
