import { getPortalContext, canManageBilling } from "@/lib/portal/context";
import { getPortalData } from "@/lib/portal/data";
import { date, DemoAction, money, PageHeading, PreviewNotice, SectionCard, StatusChip, TextLink } from "@/components/portal/PortalUI";
import BillingPaymentCenter from "@/components/portal/BillingPaymentCenter";
import { env } from "cloudflare:workers";
import { managedAchFeeCents } from "@/lib/portal/payment-domain";

export default async function BillingPage() {
  const { organization, role } = await getPortalContext(); const data = await getPortalData(organization.id);
  const balance = data.invoices.reduce((sum, row) => sum + row.invoice.balance, 0); const defaultMethod = data.paymentMethods.find((method) => method.isDefault);
  return <><PageHeading eyebrow="BILLING" title="A clear view of what’s due" description="Balances, scheduled charges, payments, and billing preferences in one place." action={canManageBilling(role) ? <DemoAction>Pay now</DemoAction> : undefined} />
    <PreviewNotice>Stripe test mode only. Card and bank details go directly to Stripe; 2Nspira stores masked metadata and provider references only.</PreviewNotice>
    <section className="portal-billing-hero"><div><span>Current balance</span><strong>{money(balance)}</strong><small>{balance ? "Payment provider connection required to pay online" : "No payment is currently due"}</small></div><div><span>Autopay</span><strong>{data.autopay ? "On" : "Off"}</strong><small>{data.autopay ? "Explicit authorization recorded" : "Not enabled"}</small></div><div><span>Default method</span><strong>{defaultMethod ? `${defaultMethod.brand} •••• ${defaultMethod.lastFour}` : "Not set"}</strong><small><TextLink href="/account/payment-methods">Manage methods</TextLink></small></div></section>
    <div className="portal-two-column"><SectionCard title="Upcoming charges" subtitle="Based on active engagement billing dates."><div className="portal-list">{data.engagements.filter((row) => row.engagement.nextBillingDate).map(({ engagement, service }) => <div className="portal-list-row" key={engagement.id}><div><strong>{service.name}</strong><span>{date(engagement.nextBillingDate)}</span></div><strong>{engagement.amount ? money(engagement.amount) : "TBD"}</strong></div>)}</div></SectionCard><SectionCard title="Billing contact"><dl className="portal-detail-list"><div><dt>Organization</dt><dd>{organization.name}</dd></div><div><dt>Email</dt><dd>{organization.billingEmail}</dd></div><div><dt>Role</dt><dd>{role.replaceAll("_", " ")}</dd></div></dl></SectionCard></div>
    <SectionCard title="Payment history" action={<TextLink href="/account/invoices">View invoices</TextLink>}><div className="portal-table" role="table" aria-label="Payment history"><div className="portal-table-head" role="row"><span>Date</span><span>Method</span><span>Amount</span><span>Status</span></div>{data.payments.map(({ payment, method }) => <div className="portal-table-row" role="row" key={payment.id}><span data-label="Date">{date(payment.paidAt)}</span><span data-label="Method">{method ? `${method.brand} •••• ${method.lastFour}` : "Manual"}</span><strong data-label="Amount">{money(payment.amount)}</strong><span data-label="Status"><StatusChip status={payment.status} /></span></div>)}</div></SectionCard>
    <SectionCard title="Payment methods and invoice payment" subtitle="Choose saved card, managed ACH, manual bank transfer, or Zelle. Fees are disclosed separately before authorization."><BillingPaymentCenter canManage={canManageBilling(role)} managedAchFeeCents={managedAchFeeCents(env.MANAGED_ACH_FEE_CENTS)} cardFeeBasisPoints={Number(env.CARD_FEE_BPS ?? 0)} methods={data.paymentMethods} invoices={data.invoices.filter(({ invoice }) => invoice.balance > 0).map(({ invoice }) => ({ id: invoice.id, invoiceNumber: invoice.invoiceNumber, balance: invoice.balance, dueDate: invoice.dueDate, status: invoice.status }))} /></SectionCard>
  </>;
}
