import index from "@/content/posts/index.json";
import post0 from "@/content/posts/the-great-ai-decentralization.json";
import post1 from "@/content/posts/the-concept-of-work-is-changing-moving-from-doing-the-actual-work-to-directing-the-ai.json";
import post2 from "@/content/posts/the-0-trillion-ai-trap.json";
import post3 from "@/content/posts/operational-ai-doesn-t-fail-because-of-technology-it-fails-because-of-how-organizations-think.json";
import post4 from "@/content/posts/building-ai-team-multi-agent-workflow-lessons.json";
import post5 from "@/content/posts/when-ai-took-the-tasks-human-judgment-became-the-work.json";
import post6 from "@/content/posts/website-design-strategies-for-impact-guide.json";
import post7 from "@/content/posts/ai-literacy-for-leaders-core-leadership-competency.json";
import post8 from "@/content/posts/re-engage-a-disengaged-team.json";
import post9 from "@/content/posts/igniting-innovation-in-small-businesses-innovative-solutions-for-small-businesses.json";
import post10 from "@/content/posts/why-silence-is-a-system-signal.json";
import post11 from "@/content/posts/why-efficiency-without-trust-creates-fragility.json";
import post12 from "@/content/posts/when-systems-work-but-trust-disappears.json";
import post13 from "@/content/posts/building-resilience-in-leadership-roles-embracing-resilient-leadership-traits.json";
import post14 from "@/content/posts/building-resilience-in-leadership-roles-essential-resilient-leadership-traits.json";
import post15 from "@/content/posts/why-innovation-feels-harder-in-2025-and-what-great-leaders-do-differently.json";
import post16 from "@/content/posts/achieve-business-goals-with-aligning-it-with-business.json";
import post17 from "@/content/posts/ai-overload-in-2025-why-people-are-turning-ai-off-and-what-leaders-really-need.json";
import post18 from "@/content/posts/the-tuesday-that-taught-me-everything-about-trust.json";
import post19 from "@/content/posts/the-real-digital-transformation-killing-the-systems-you-re-afraid-to-touch.json";
import post20 from "@/content/posts/the-human-side-of-technology-resilience-reinvention-and-my-journey-toward-leadership.json";
import post21 from "@/content/posts/neurodiversity-aithe-untapped-superpower-of-2025-for-organizations.json";
import post22 from "@/content/posts/from-paper-folders-to-digital-confidence-a-story-of-trust-brains-and-the-real-work-of-change.json";
import post23 from "@/content/posts/designing-for-what-matters.json";
import post24 from "@/content/posts/beyond-the-hype-why-emotional-ai-will-define-the-next-decade-of-human-computer-interaction.json";

export const posts = index;
export const fullPosts = [post0, post1, post2, post3, post4, post5, post6, post7, post8, post9, post10, post11, post12, post13, post14, post15, post16, post17, post18, post19, post20, post21, post22, post23, post24];
export const getPost = (slug: string) => fullPosts.find(post => post.slug === slug);
export const displayDate = (date: string) => new Intl.DateTimeFormat("en-US", { dateStyle: "long", timeZone: "UTC" }).format(new Date(date));
