import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
export const metadata:Metadata={title:"From the Author | Books & Visual Essays",description:"Explore Trust Is the Operating System, leadership reflections, audio, and visual essays by Jeffrey Cortez.",alternates:{canonical:"/books"}};
export default function BooksPage(){return <main className="flex-1 bg-zinc-50 dark:bg-black">
  <header className="mx-auto max-w-4xl px-4 py-20 sm:px-6"><p className="text-sm font-semibold uppercase tracking-widest text-blue-700 dark:text-blue-400">From the author</p><h1 className="mt-4 text-4xl font-bold tracking-tight text-zinc-900 dark:text-white sm:text-5xl">Leadership Books & Visual Essays</h1><p className="mt-6 text-lg leading-8 text-zinc-600 dark:text-zinc-300">Explore clarity, restraint, and leadership through different mediums. Each piece is an invitation to think about how trust, judgment, and meaning shape modern organizations.</p></header>
  <div className="mx-auto max-w-6xl px-4 pb-20 sm:px-6"><section className="grid gap-10 rounded-2xl border border-zinc-200 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-950 sm:p-10 md:grid-cols-[1fr_2fr]" aria-labelledby="book-title"><Image src="/images/books/trust-is-the-operating-system.jpg" alt="Cover of Trust Is the Operating System by Jeffrey Cortez" width={1600} height={2560} unoptimized className="mx-auto h-auto w-full max-w-xs rounded-lg" /><div><h2 id="book-title" className="text-3xl font-bold text-zinc-900 dark:text-white">Trust Is the Operating System</h2><div className="mt-6 space-y-4 leading-7 text-zinc-600 dark:text-zinc-300"><p>Most organizations aren’t failing. They’re functioning.</p><p>Systems run. Dashboards glow green. AI optimizes faster than judgment can keep up. And yet, something feels increasingly fragile.</p><p>This book examines leadership in an AI-saturated world where efficiency has quietly replaced coherence—and trust has become invisible infrastructure.</p><p>Written by a technology executive and educator, it explores why capable teams hesitate long before performance declines, why optimization creates fragility rather than scale, and what leaders must protect as automation increases.</p></div><a href="https://amzn.to/4sVBcuF" rel="sponsored" className="mt-6 inline-block rounded-lg bg-blue-700 px-6 py-3 font-semibold text-white hover:bg-blue-800">View the book on Amazon →</a><p className="mt-3 text-sm text-zinc-600 dark:text-zinc-400">Supporting affiliate link. Proceeds help sustain independent publishing and research.</p><Link href="/blog/categories/trust-is-the-operating-system" className="mt-4 inline-block rounded font-semibold text-blue-700 underline dark:text-blue-400">Read selected excerpts →</Link></div></section>
  <section className="mt-10 rounded-2xl border border-zinc-200 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-950 sm:p-10" aria-labelledby="audio-title"><h2 id="audio-title" className="text-2xl font-semibold text-zinc-900 dark:text-white">When Systems Work, Trust Weakens</h2><p className="mt-3 text-zinc-600 dark:text-zinc-300">A 13-minute conversation on leadership, AI, and judgment.</p><audio controls preload="none" aria-label="When Systems Work, Trust Weakens" className="mt-6 w-full"><source src="/audio/when-systems-work-trust-weakens.mp3" type="audio/mpeg" /><a href="/audio/when-systems-work-trust-weakens.mp3">Listen to the audio</a></audio></section>
  <section className="mt-10 grid gap-8 rounded-2xl border border-zinc-200 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-950 sm:p-10 md:grid-cols-2" aria-labelledby="print-title"><Image src="/images/books/reduce-the-noise.png" alt="Reduce the Noise. Strengthen the Signal. — visual essay print" width={1014} height={1522} unoptimized className="mx-auto h-auto w-full max-w-xs rounded-lg" /><div className="self-center"><p className="text-sm font-semibold uppercase tracking-wider text-blue-700 dark:text-blue-400">Visual essays</p><h2 id="print-title" className="mt-4 text-3xl font-bold text-zinc-900 dark:text-white">Reduce the Noise. Strengthen the Signal.</h2><p className="mt-6 leading-7 text-zinc-600 dark:text-zinc-300">A visual meditation on clarity, focus, and leadership in an increasingly noisy world.</p><a href="https://2nspira.etsy.com/listing/4437231821/reduce-the-noise-strengthen-the-signal" className="mt-6 inline-block rounded font-semibold text-blue-700 underline dark:text-blue-400">View the print on Etsy →</a></div></section></div>
</main>;}
